version: '3'
services:
  trial-config-service:
    build: .
    image: ghcr.io/ndph-arts/trial-config-service
    container_name: trial-config-service-mts-ui
    depends_on:
      - postgres
      - global-trial-config-mock
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://trial-config-service/swagger-ui/ || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/arts?user=ndph@arts-db&password=England99!
      JDBC_DRIVER: "org.postgresql.Driver"
      SERVER_PORT: "80"
    ports:
      - "80:80"

  mts-trial-ui:
    image: mts-trial-ui-dev
    container_name: mts-trial-ui-dev
    ports:
      - "4200:4200"
    volumes:
      - $PWD:/app

  global-trial-config-mock:
    image: ghcr.io/ndph-arts/global-trial-config-mock
    container_name: global-trial-config-mock-mts-ui
    ports:
      - "8085:8085"
    volumes:
     - .:/tmp

  mts-translation-service:
    image: ghcr.io/ndph-arts/mts-translation-service
    container_name: mts-translation-service-mts-ui
    depends_on:
      - postgres
      - global-trial-config-mock
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://trial-config-service/swagger-ui/ || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/arts?user=ndph@arts-db&password=password
      JDBC_DRIVER: "org.postgresql.Driver"
      SERVER_PORT: 81
    ports:
      - "81:81"

  postgres:
    image: postgres
    container_name: postgres-mts-ui
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "ndph@arts-db"
      POSTGRES_DB: "arts"
    ports:
      - "5432:5432"
